# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

UserType.create(type_name: 'superuser')
UserType.create(type_name: 'student')
UserType.create(type_name: 'warden')
UserType.create(type_name: 'maintenance secretary')
UserType.create(type_name: 'electrician')
UserType.create(type_name: 'plumber')
UserType.create(type_name: 'sweeper')
UserType.create(type_name: 'ug section')
UserType.create(type_name: 'dean')

User.create(name:'superuser',user_type_id: UserType.find_by(type_name: 'superuser').id,group: 0,login_username: 'su',login_password: 'su')
User.create(name:'surag',user_type_id: UserType.find_by(type_name: 'student').id,group: 1,login_username: 'surag',login_password: 'surag')
User.create(name:'shanti',user_type_id: UserType.find_by(type_name: 'student').id,group: 1,login_username: 'shanti',login_password: 'shanti')
User.create(name:'karan',user_type_id: UserType.find_by(type_name: 'student').id,group: 2,login_username: 'karan',login_password: 'karan')
User.create(name:'kara_boy',user_type_id: UserType.find_by(type_name: 'student').id,group: 2,login_username: 'kara_boy',login_password: 'kara_boy')
User.create(name:'warden_ara',user_type_id: UserType.find_by(type_name: 'warden').id,group: 1,login_username: 'warden_ara',login_password: 'warden_ara')
User.create(name:'maintara',user_type_id: UserType.find_by(type_name: 'maintenance secretary').id,group: 1,login_username: 'maintara',login_password: 'maintara')
User.create(name:'warden_kara',user_type_id: UserType.find_by(type_name: 'warden').id,group: 2,login_username: 'warden_kara',login_password: 'warden_kara')
User.create(name:'maintkara',user_type_id: UserType.find_by(type_name: 'maintenance secretary').id,group: 2,login_username: 'maintkara',login_password: 'maintkara')
User.create(name:'electara',user_type_id: UserType.find_by(type_name: 'electrician').id,group: 1,login_username: 'electara',login_password: 'electara')
User.create(name:'plumbara',user_type_id: UserType.find_by(type_name: 'plumber').id,group: 1,login_username: 'plumbara',login_password: 'plumbara')
User.create(name:'ug boss',user_type_id: UserType.find_by(type_name: 'ug section').id,group: 0,login_username: 'ug',login_password: 'ug')
User.create(name:'vinay',user_type_id: UserType.find_by(type_name: 'student').id,group: 3,login_username: 'vinay',login_password: 'vinay')
User.create(name:'mrravi',user_type_id: UserType.find_by(type_name: 'dean').id,group: 0,login_username: 'ravi',login_password: 'ravi')
User.create(name:'singla',user_type_id: UserType.find_by(type_name: 'student').id,group: 2,login_username: 'singla',login_password: 'singla')
User.create(name:'chaman',user_type_id: UserType.find_by(type_name: 'sweeper').id,group: 2,login_username: 'chaman',login_password: 'chaman')
User.create(name:'chaman',user_type_id: UserType.find_by(type_name: 'sweeper').id,group: 1,login_username: 'chaman',login_password: 'chaman')
User.create(name:'sid',user_type_id: UserType.find_by(type_name: 'plumber').id,group: 3,login_username: 'sid',login_password: 'sid')
User.create(name:'shampoo',user_type_id: UserType.find_by(type_name: 'electrician').id,group: 1,login_username: 'shampoo',login_password: 'shampoo')
User.create(name:'amit',user_type_id: UserType.find_by(type_name: 'maintenance secretary').id,group: 3,login_username: 'amit',login_password: 'amit')
User.create(name:'paul',user_type_id: UserType.find_by(type_name: 'student').id,group: 3,login_username: 'paul',login_password: 'paul')
User.create(name:'yash',user_type_id: UserType.find_by(type_name: 'student').id,group: 3,login_username: 'yash',login_password: 'yash')
User.create(name:'chhabra',user_type_id: UserType.find_by(type_name: 'student').id,group: 2,login_username: 'chhabra',login_password: 'chhabra')
User.create(name:'lalu',user_type_id: UserType.find_by(type_name: 'student').id,group: 3,login_username: 'lalu',login_password: 'lalu')
User.create(name:'mausam',user_type_id: UserType.find_by(type_name: 'student').id,group: 3,login_username: 'mausam',login_password: 'mausam')
User.create(name:'parag',user_type_id: UserType.find_by(type_name: 'student').id,group: 3,login_username: 'parag',login_password: 'parag')
User.create(name:'sandy',user_type_id: UserType.find_by(type_name: 'student').id,group: 1,login_username: 'sandy',login_password: 'sandy')
User.create(name:'aman',user_type_id: UserType.find_by(type_name: 'student').id,group: 2,login_username: 'aman',login_password: 'aman')
User.create(name:'didi',user_type_id: UserType.find_by(type_name: 'student').id,group: 1,login_username: 'didi',login_password: 'didi')
User.create(name:'chandan',user_type_id: UserType.find_by(type_name: 'student').id,group: 2,login_username: 'chandan',login_password: 'chandan')
User.create(name:'barun',user_type_id: UserType.find_by(type_name: 'student').id,group: 2,login_username: 'barun',login_password: 'barun')
User.create(name:'ved',user_type_id: UserType.find_by(type_name: 'student').id,group: 1,login_username: 'ved',login_password: 'ved')
User.create(name:'mittal',user_type_id: UserType.find_by(type_name: 'student').id,group: 1,login_username: 'mittal',login_password: 'mittal')
User.create(name:'sapra',user_type_id: UserType.find_by(type_name: 'student').id,group: 2,login_username: 'sapra',login_password: 'sapra')
User.create(name:'warden_nil',user_type_id: UserType.find_by(type_name: 'warden').id,group: 3,login_username: 'warden_nil',login_password: 'warden_nil')

ComplaintType.create(level: 1, type_name: 'tubelight', resolving_user_types: [UserType.find_by(type_name: 'student').id, nil], action_user_types: [UserType.find_by(type_name: 'maintenance secretary').id,UserType.find_by(type_name: 'warden').id,UserType.find_by(type_name: 'electrician').id, nil])
ComplaintType.create(level: 2, type_name: 'toilets', resolving_user_types: [UserType.find_by(type_name: 'warden').id, nil], action_user_types: [UserType.find_by(type_name: 'maintenance secretary').id,UserType.find_by(type_name: 'warden').id,UserType.find_by(type_name: 'plumber').id, nil])
ComplaintType.create(level: 1, type_name: 'fees', resolving_user_types: [UserType.find_by(type_name: 'student').id, nil], action_user_types: [UserType.find_by(type_name: 'ug section').id, nil])
ComplaintType.create(level: 3, type_name: 'LAN ban', resolving_user_types: [UserType.find_by(type_name: 'dean').id, nil], action_user_types: [UserType.find_by(type_name: 'dean').id, nil])
ComplaintType.create(level: 1, type_name: 'mess', resolving_user_types: [UserType.find_by(type_name: 'warden').id, nil], action_user_types: [UserType.find_by(type_name: 'maintenance secretary').id, UserType.find_by(type_name: 'warden').id, nil])
ComplaintType.create(level: 3, type_name: 'Proxy Increase', resolving_user_types: [UserType.find_by(type_name: 'dean').id, nil], action_user_types: [UserType.find_by(type_name: 'dean').id, nil])
